const siteImages = {
    featured: [
        'images/featured1.jpg',
        'images/featured2.jpg',
        'images/featured3.jpg',
        'images/featured4.jpg'
    ],
    qrcode: 'images/qrcode.png'
};

const projectsData = [
    {
        "id": 1788513859922,
        "sortOrder": 1,
        "isTop": false,
        "title": "AIGC",
        "category": "aigc",
        "categoryName": "AIGC",
        "displayStyle": "B",
        "image": "images/cases/AIGC/00023-725325415.jpg",
        "gallery": [
            "images/cases/AIGC/00023-725325415.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859923,
        "sortOrder": 3,
        "isTop": false,
        "title": "UI动画",
        "category": "ui",
        "categoryName": "UI设计",
        "displayStyle": "B",
        "image": "images/cases/UI动画/3gif-icons-menu-transition-animations-shortlist.gif",
        "gallery": [
            "images/cases/UI动画/3gif-icons-menu-transition-animations-shortlist.gif",
            "images/cases/UI动画/0147fe56d92d066ac7252ce67cc81a.gif",
            "images/cases/UI动画/加载动画.gif",
            "images/cases/UI动画/gif-icons-menu-transition-animations-distant-audio-recordings.gif",
            "images/cases/UI动画/gif-icons-menu-transition-animations-play.gif",
            "images/cases/UI动画/iPhone-Mockup.gif",
            "images/cases/UI动画/WIFI.gif"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859924,
        "sortOrder": 5,
        "isTop": false,
        "title": "WEB",
        "category": "ui",
        "categoryName": "UI设计",
        "displayStyle": "B",
        "image": "images/cases/WEB/外设.jpg",
        "gallery": [
            "images/cases/WEB/外设.jpg",
            "images/cases/WEB/新春外设电商.jpg",
            "images/cases/WEB/AR眼镜.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859925,
        "sortOrder": 7,
        "isTop": false,
        "title": "切片软件界面设计",
        "category": "ui",
        "categoryName": "UI设计",
        "displayStyle": "B",
        "image": "images/cases/切片软件界面设计/弹窗.jpg",
        "gallery": [
            "images/cases/切片软件界面设计/弹窗.jpg",
            "images/cases/切片软件界面设计/切片后.jpg",
            "images/cases/切片软件界面设计/切片软件开机界面.jpg",
            "images/cases/切片软件界面设计/首页-移动.jpg",
            "images/cases/切片软件界面设计/文件列表.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859926,
        "sortOrder": 9,
        "isTop": false,
        "title": "官网web设计",
        "category": "ui",
        "categoryName": "UI设计",
        "displayStyle": "B",
        "image": "images/cases/官网web设计/image19.jpeg",
        "gallery": [
            "images/cases/官网web设计/image19.jpeg",
            "images/cases/官网web设计/image20.jpeg",
            "images/cases/官网web设计/image21.jpeg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859927,
        "sortOrder": 11,
        "isTop": false,
        "title": "雕刻机app界面设计",
        "category": "ui",
        "categoryName": "UI设计",
        "displayStyle": "B",
        "image": "images/cases/雕刻机app界面设计/1.jpg",
        "gallery": [
            "images/cases/雕刻机app界面设计/1.jpg",
            "images/cases/雕刻机app界面设计/裁切-自由.jpg",
            "images/cases/雕刻机app界面设计/创作-绘画.jpg",
            "images/cases/雕刻机app界面设计/雕刻设置2.jpg",
            "images/cases/雕刻机app界面设计/机型／蓝牙连接.jpg",
            "images/cases/雕刻机app界面设计/开机界面.jpg",
            "images/cases/雕刻机app界面设计/开始预览.jpg",
            "images/cases/雕刻机app界面设计/IMG_6268 iPhone X mockup.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859928,
        "sortOrder": 13,
        "isTop": false,
        "title": "3D打印其他",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/3D打印其他/A1_40661ea6.jpg",
        "gallery": [
            "images/cases/3D打印其他/A1_40661ea6.jpg",
            "images/cases/3D打印其他/A1.jpg",
            "images/cases/3D打印其他/A2_7d8b0052.jpg",
            "images/cases/3D打印其他/A2_e81216ea.jpg",
            "images/cases/3D打印其他/A2_ff7efa7a.jpg",
            "images/cases/3D打印其他/A2.jpg",
            "images/cases/3D打印其他/A3.jpg",
            "images/cases/3D打印其他/A4.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859929,
        "sortOrder": 15,
        "isTop": false,
        "title": "3D打印耗材",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/3D打印耗材/未标题-3.jpg",
        "gallery": [
            "images/cases/3D打印耗材/未标题-3.jpg",
            "images/cases/3D打印耗材/未标题-10.jpg",
            "images/cases/3D打印耗材/未标题-14.jpg",
            "images/cases/3D打印耗材/未标题-16.jpg",
            "images/cases/3D打印耗材/未标题-17.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859930,
        "sortOrder": 17,
        "isTop": false,
        "title": "3D渲染-散图",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/3D渲染-散图/500ml.jpg",
        "gallery": [
            "images/cases/3D渲染-散图/500ml.jpg",
            "images/cases/3D渲染-散图/1000ml.jpg",
            "images/cases/3D渲染-散图/3554-1.jpg",
            "images/cases/3D渲染-散图/场景banner.jpg",
            "images/cases/3D渲染-散图/树脂.jpg",
            "images/cases/3D渲染-散图/秩序之光.jpg",
            "images/cases/3D渲染-散图/主要 拷贝.jpg",
            "images/cases/3D渲染-散图/A35.jpg",
            "images/cases/3D渲染-散图/A36.jpg",
            "images/cases/3D渲染-散图/A37.jpg",
            "images/cases/3D渲染-散图/A38.jpg",
            "images/cases/3D渲染-散图/image1.jpg",
            "images/cases/3D渲染-散图/image2.jpg",
            "images/cases/3D渲染-散图/image4.jpg",
            "images/cases/3D渲染-散图/image7.jpg",
            "images/cases/3D渲染-散图/lADPBFuNc9K8RqrNBDjNB4A_1920_1080.jpg",
            "images/cases/3D渲染-散图/lADPBGnDbmYWonPNC7jNC7g_3000_3000.jpg",
            "images/cases/3D渲染-散图/lADPBGY178FUQsDNC7jNC7g_3000_3000.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859931,
        "sortOrder": 19,
        "isTop": false,
        "title": "A10",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/A10/背面.jpg",
        "gallery": [
            "images/cases/A10/背面.jpg",
            "images/cases/A10/底部图.jpg",
            "images/cases/A10/顶部图.jpg",
            "images/cases/A10/热床打开图.jpg",
            "images/cases/A10/特写.jpg",
            "images/cases/A10/液晶屏幕特写.jpg",
            "images/cases/A10/主图1.jpg",
            "images/cases/A10/image8.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859932,
        "sortOrder": 21,
        "isTop": false,
        "title": "A5",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/A5/A1.jpg",
        "gallery": [
            "images/cases/A5/A1.jpg",
            "images/cases/A5/A14.jpg",
            "images/cases/A5/A15.jpg",
            "images/cases/A5/A16.jpg",
            "images/cases/A5/A17.jpg",
            "images/cases/A5/A18.jpg",
            "images/cases/A5/A19.jpg",
            "images/cases/A5/A20.jpg",
            "images/cases/A5/A21.jpg",
            "images/cases/A5/A22.jpg",
            "images/cases/A5/A23.jpg",
            "images/cases/A5/A24.jpg",
            "images/cases/A5/A25.jpg",
            "images/cases/A5/A26.jpg",
            "images/cases/A5/A27.jpg",
            "images/cases/A5/A28.jpg",
            "images/cases/A5/A29.jpg",
            "images/cases/A5/A30.jpg",
            "images/cases/A5/A31.jpg",
            "images/cases/A5/A32.jpg",
            "images/cases/A5/A33.jpg",
            "images/cases/A5/A34.jpg",
            "images/cases/A5/A35.jpg",
            "images/cases/A5/A36.jpg",
            "images/cases/A5/A37.jpg",
            "images/cases/A5/A38.jpg",
            "images/cases/A5/A39.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859933,
        "sortOrder": 23,
        "isTop": false,
        "title": "A8Plus",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/A8Plus/A8-Plus-1.jpg",
        "gallery": [
            "images/cases/A8Plus/A8-Plus-1.jpg",
            "images/cases/A8Plus/A8-Plus-2.jpg",
            "images/cases/A8Plus/A8-Plus-4.jpg",
            "images/cases/A8Plus/A8-Plus-5.jpg",
            "images/cases/A8Plus/A8-Plus-6-1.jpg",
            "images/cases/A8Plus/A8-Plus-6.jpg",
            "images/cases/A8Plus/A8-Plus-7.jpg",
            "images/cases/A8Plus/A8-Plus-10.jpg",
            "images/cases/A8Plus/A8-Plus-11.jpg",
            "images/cases/A8Plus/A8-Plus-12.jpg",
            "images/cases/A8Plus/A8-Plus-13.jpg",
            "images/cases/A8Plus/A8-Plus-14.jpg",
            "images/cases/A8Plus/A21.jpg",
            "images/cases/A8Plus/A23.jpg",
            "images/cases/A8Plus/A25.jpg",
            "images/cases/A8Plus/A26.jpg",
            "images/cases/A8Plus/B25.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859934,
        "sortOrder": 25,
        "isTop": false,
        "title": "DLP",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/DLP/A1 拷贝.jpg",
        "gallery": [
            "images/cases/DLP/A1 拷贝.jpg",
            "images/cases/DLP/A2 拷贝.jpg",
            "images/cases/DLP/A3 拷贝.jpg",
            "images/cases/DLP/A4 拷贝.jpg",
            "images/cases/DLP/A5 拷贝.jpg",
            "images/cases/DLP/A6 拷贝.jpg",
            "images/cases/DLP/lADPBE1XeT_hhEXNA-jNA-g_1000_1000.jpg",
            "images/cases/DLP/lADPBFRydoluCFDNA-jNA-g_1000_1000.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859935,
        "sortOrder": 27,
        "isTop": false,
        "title": "E12PLUS",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/E12PLUS/A1_0001.jpg",
        "gallery": [
            "images/cases/E12PLUS/A1_0001.jpg",
            "images/cases/E12PLUS/A2_0001.jpg",
            "images/cases/E12PLUS/A3_0001.jpg",
            "images/cases/E12PLUS/A4_0001.jpg",
            "images/cases/E12PLUS/A5_0001.jpg",
            "images/cases/E12PLUS/A18X1000.jpg",
            "images/cases/E12PLUS/B1_0000.jpg",
            "images/cases/E12PLUS/B16_0001.jpg",
            "images/cases/E12PLUS/image9.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859936,
        "sortOrder": 29,
        "isTop": false,
        "title": "ET4",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/ET4/A1.jpg",
        "gallery": [
            "images/cases/ET4/A1.jpg",
            "images/cases/ET4/A2.jpg",
            "images/cases/ET4/A3.jpg",
            "images/cases/ET4/A4.jpg",
            "images/cases/ET4/A5.jpg",
            "images/cases/ET4/A6.jpg",
            "images/cases/ET4/A7.jpg",
            "images/cases/ET4/A8.jpg",
            "images/cases/ET4/A9.jpg",
            "images/cases/ET4/A10.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859937,
        "sortOrder": 31,
        "isTop": false,
        "title": "LC100",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/LC100/5.jpg",
        "gallery": [
            "images/cases/LC100/5.jpg",
            "images/cases/LC100/5c4f8b92c90449a507268c1d23c83231.jpg",
            "images/cases/LC100/32.jpg",
            "images/cases/LC100/A0_0269.jpg",
            "images/cases/LC100/ab4d1fe1abd698324137b0d0edd5ec7d.jpg",
            "images/cases/LC100/Creator-Devices-2.jpg",
            "images/cases/LC100/Creator-Devices-6.jpg",
            "images/cases/LC100/Creator-Devices-7.jpg",
            "images/cases/LC100/lADPBFf_9S3_AKHNBDjNB4A_1920_1080.jpg",
            "images/cases/LC100/LaserCube LC100 Portable Laser Engraving Machine Featured_.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859938,
        "sortOrder": 33,
        "isTop": false,
        "title": "N4",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/N4/2.jpg",
        "gallery": [
            "images/cases/N4/2.jpg",
            "images/cases/N4/3.jpg",
            "images/cases/N4/4.jpg",
            "images/cases/N4/7.jpg",
            "images/cases/N4/8.jpg",
            "images/cases/N4/8~1.jpg",
            "images/cases/N4/9.jpg",
            "images/cases/N4/2244.jpg",
            "images/cases/N4/带彩色模型.jpg",
            "images/cases/N4/中文界面主图4.jpg",
            "images/cases/N4/中文界面主图5.jpg",
            "images/cases/N4/中文界面主图6.jpg",
            "images/cases/N4/A7.jpg",
            "images/cases/N4/A8.jpg",
            "images/cases/N4/A16~1.jpg",
            "images/cases/N4/A17~1.jpg",
            "images/cases/N4/A18~1.jpg",
            "images/cases/N4/A20~1.jpg",
            "images/cases/N4/A23~1.jpg",
            "images/cases/N4/A24~1.jpg",
            "images/cases/N4/A26~1.jpg",
            "images/cases/N4/A32~1.jpg",
            "images/cases/N4/A33~1.jpg",
            "images/cases/N4/A35~1.jpg",
            "images/cases/N4/A36~1.jpg",
            "images/cases/N4/A39~1.jpg",
            "images/cases/N4/A50-2.jpg",
            "images/cases/N4/A51.jpg",
            "images/cases/N4/KG405.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859939,
        "sortOrder": 35,
        "isTop": false,
        "title": "N7",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/N7/A1.jpg",
        "gallery": [
            "images/cases/N7/A1.jpg",
            "images/cases/N7/A2.jpg",
            "images/cases/N7/A3.jpg",
            "images/cases/N7/A4.jpg",
            "images/cases/N7/A6.jpg",
            "images/cases/N7/A7.jpg",
            "images/cases/N7/A8.jpg",
            "images/cases/N7/A9.jpg",
            "images/cases/N7/A10.jpg",
            "images/cases/N7/A11.jpg",
            "images/cases/N7/A12.jpg",
            "images/cases/N7/A13.jpg",
            "images/cases/N7/A15.jpg",
            "images/cases/N7/A16.jpg",
            "images/cases/N7/A17.jpg",
            "images/cases/N7/A18.jpg",
            "images/cases/N7/A19.jpg",
            "images/cases/N7/A20.jpg",
            "images/cases/N7/A21.jpg",
            "images/cases/N7/A22.jpg",
            "images/cases/N7/A23.jpg",
            "images/cases/N7/A24.jpg",
            "images/cases/N7/A25.jpg",
            "images/cases/N7/A26.jpg",
            "images/cases/N7/A27.jpg",
            "images/cases/N7/A28.jpg",
            "images/cases/N7/A29.jpg",
            "images/cases/N7/A30.jpg",
            "images/cases/N7/A31.jpg",
            "images/cases/N7/A32.jpg",
            "images/cases/N7/A33.jpg",
            "images/cases/N7/A34.jpg",
            "images/cases/N7/AFWEAGE.jpg",
            "images/cases/N7/image6.jpeg",
            "images/cases/N7/image6.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859940,
        "sortOrder": 37,
        "isTop": false,
        "title": "T200S",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/T200S/A1.jpg",
        "gallery": [
            "images/cases/T200S/A1.jpg",
            "images/cases/T200S/A2.jpg",
            "images/cases/T200S/A3.jpg",
            "images/cases/T200S/A4.jpg",
            "images/cases/T200S/A5.jpg",
            "images/cases/T200S/A6.jpg",
            "images/cases/T200S/B1.jpg",
            "images/cases/T200S/B2.jpg",
            "images/cases/T200S/B3.jpg",
            "images/cases/T200S/lADPBGKocRxQW-zNBDjNB4A_1920_1080.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859941,
        "sortOrder": 39,
        "isTop": false,
        "title": "VP01",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/VP01/2-1.jpg",
        "gallery": [
            "images/cases/VP01/2-1.jpg",
            "images/cases/VP01/2-2.jpg",
            "images/cases/VP01/2-3.jpg",
            "images/cases/VP01/A2.jpg",
            "images/cases/VP01/A4.jpg",
            "images/cases/VP01/A5.jpg",
            "images/cases/VP01/A6.jpg",
            "images/cases/VP01/A7.jpg",
            "images/cases/VP01/A8.jpg",
            "images/cases/VP01/A9.jpg",
            "images/cases/VP01/A10.jpg",
            "images/cases/VP01/A11.jpg",
            "images/cases/VP01/A12.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859942,
        "sortOrder": 41,
        "isTop": false,
        "title": "VP05",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/VP05/1-2.jpg",
        "gallery": [
            "images/cases/VP05/1-2.jpg",
            "images/cases/VP05/1-3.jpg",
            "images/cases/VP05/1-4.jpg",
            "images/cases/VP05/1-5.jpg",
            "images/cases/VP05/1-6.jpg",
            "images/cases/VP05/1-7.jpg",
            "images/cases/VP05/1-8.jpg",
            "images/cases/VP05/1-10.jpg",
            "images/cases/VP05/A1.jpg",
            "images/cases/VP05/A2.jpg",
            "images/cases/VP05/A3.jpg",
            "images/cases/VP05/A4.jpg",
            "images/cases/VP05/A5.jpg",
            "images/cases/VP05/A6.jpg",
            "images/cases/VP05/A7.jpg",
            "images/cases/VP05/A8.jpg",
            "images/cases/VP05/A9.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859943,
        "sortOrder": 43,
        "isTop": false,
        "title": "耗材",
        "category": "3d",
        "categoryName": "3D渲染",
        "displayStyle": "B",
        "image": "images/cases/耗材/橙色.jpg",
        "gallery": [
            "images/cases/耗材/橙色.jpg",
            "images/cases/耗材/橙色2.jpg",
            "images/cases/耗材/粉色.jpg",
            "images/cases/耗材/粉色2.jpg",
            "images/cases/耗材/黄色.jpg",
            "images/cases/耗材/黄色2.jpg",
            "images/cases/耗材/蓝色.jpg",
            "images/cases/耗材/蓝色2.jpg",
            "images/cases/耗材/绿色.jpg",
            "images/cases/耗材/绿色2.jpg",
            "images/cases/耗材/透明.jpg",
            "images/cases/耗材/透明2.jpg",
            "images/cases/耗材/银色.jpg",
            "images/cases/耗材/银色2.jpg",
            "images/cases/耗材/A2_0060.jpg",
            "images/cases/耗材/A5.jpg",
            "images/cases/耗材/A18.jpg",
            "images/cases/耗材/A25.jpg",
            "images/cases/耗材/A26.jpg",
            "images/cases/耗材/A27.jpg",
            "images/cases/耗材/A28.jpg",
            "images/cases/耗材/ABS-Filament-1.jpg",
            "images/cases/耗材/ABS-Filament-2.jpg",
            "images/cases/耗材/ABS-Filament-3.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859944,
        "sortOrder": 45,
        "isTop": false,
        "title": "工矿灯",
        "category": "photography",
        "categoryName": "产品摄影",
        "displayStyle": "B",
        "image": "images/cases/工矿灯/1_b5d932f1.jpg",
        "gallery": [
            "images/cases/工矿灯/1_b5d932f1.jpg",
            "images/cases/工矿灯/3.jpg",
            "images/cases/工矿灯/4_9a4e924f.jpg",
            "images/cases/工矿灯/7.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859945,
        "sortOrder": 47,
        "isTop": false,
        "title": "灯泡",
        "category": "photography",
        "categoryName": "产品摄影",
        "displayStyle": "B",
        "image": "images/cases/灯泡/Main_02.jpg",
        "gallery": [
            "images/cases/灯泡/Main_02.jpg",
            "images/cases/灯泡/Main_12.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859946,
        "sortOrder": 49,
        "isTop": false,
        "title": "生活实拍",
        "category": "photography",
        "categoryName": "产品摄影",
        "displayStyle": "B",
        "image": "images/cases/生活实拍/28bfba35b010934f8a47595e26ad1336.JPG",
        "gallery": [
            "images/cases/生活实拍/28bfba35b010934f8a47595e26ad1336.JPG",
            "images/cases/生活实拍/073e0ff9392ab0937db81cdae3f7f890.JPG",
            "images/cases/生活实拍/2024_08_10_00_01_IMG_5198.JPG",
            "images/cases/生活实拍/2024_08_10_00_01_IMG_5199.JPG",
            "images/cases/生活实拍/2024_08_10_00_01_IMG_5200.JPG",
            "images/cases/生活实拍/2024_08_10_00_01_IMG_5201.JPG",
            "images/cases/生活实拍/2024_08_10_00_01_IMG_5202.JPG",
            "images/cases/生活实拍/2024_08_10_00_01_IMG_5203.JPG",
            "images/cases/生活实拍/2024_08_10_00_01_IMG_5204.JPG",
            "images/cases/生活实拍/2024_08_10_00_01_IMG_5205.JPG",
            "images/cases/生活实拍/2024_08_10_00_09_IMG_5206.JPG",
            "images/cases/生活实拍/2024_08_10_00_09_IMG_5207.JPG",
            "images/cases/生活实拍/2024_08_10_00_14_IMG_5208.JPG",
            "images/cases/生活实拍/微信图片_20240729183440.jpg",
            "images/cases/生活实拍/微信图片_20240729183441.jpg",
            "images/cases/生活实拍/微信图片_20240729183442.jpg",
            "images/cases/生活实拍/微信图片_202407291834411.jpg",
            "images/cases/生活实拍/微信图片_202407291834421.jpg",
            "images/cases/生活实拍/d132be37437c8587b68bbf1738deee59.JPG",
            "images/cases/生活实拍/DSC_3565 拷贝.jpg",
            "images/cases/生活实拍/IMG_0741.jpg",
            "images/cases/生活实拍/IMG_1168.jpg",
            "images/cases/生活实拍/IMG_1849.jpg",
            "images/cases/生活实拍/IMG_2361.jpg",
            "images/cases/生活实拍/IMG_2488.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859947,
        "sortOrder": 51,
        "isTop": false,
        "title": "筒灯",
        "category": "photography",
        "categoryName": "产品摄影",
        "displayStyle": "B",
        "image": "images/cases/筒灯/1_f2b8ecd5.jpg",
        "gallery": [
            "images/cases/筒灯/1_f2b8ecd5.jpg",
            "images/cases/筒灯/1.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859948,
        "sortOrder": 53,
        "isTop": false,
        "title": "防水灯",
        "category": "photography",
        "categoryName": "产品摄影",
        "displayStyle": "B",
        "image": "images/cases/防水灯/1.jpg",
        "gallery": [
            "images/cases/防水灯/1.jpg",
            "images/cases/防水灯/2_18772230.jpg",
            "images/cases/防水灯/2.jpg",
            "images/cases/防水灯/4.jpg",
            "images/cases/防水灯/5.jpg",
            "images/cases/防水灯/11.jpg",
            "images/cases/防水灯/12.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859949,
        "sortOrder": 55,
        "isTop": false,
        "title": "面板灯照明",
        "category": "photography",
        "categoryName": "产品摄影",
        "displayStyle": "B",
        "image": "images/cases/面板灯照明/5_d5f7bc69.jpg",
        "gallery": [
            "images/cases/面板灯照明/5_d5f7bc69.jpg",
            "images/cases/面板灯照明/IMG_0780.JPG",
            "images/cases/面板灯照明/IMG_3223.JPG",
            "images/cases/面板灯照明/IMG_3225.JPG",
            "images/cases/面板灯照明/IMG_3377.JPG",
            "images/cases/面板灯照明/IMG_3378.JPG"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859950,
        "sortOrder": 57,
        "isTop": false,
        "title": "3d打印耗材手提袋",
        "category": "packaging",
        "categoryName": "包装设计",
        "displayStyle": "B",
        "image": "images/cases/3d打印耗材手提袋/侧面2.jpg",
        "gallery": [
            "images/cases/3d打印耗材手提袋/侧面2.jpg",
            "images/cases/3d打印耗材手提袋/耗材.jpg",
            "images/cases/3d打印耗材手提袋/机器.jpg",
            "images/cases/3d打印耗材手提袋/两个袋子_333_1.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859951,
        "sortOrder": 59,
        "isTop": false,
        "title": "灯具包装盒",
        "category": "packaging",
        "categoryName": "包装设计",
        "displayStyle": "B",
        "image": "images/cases/灯具包装盒/（新地址）底发光 595595 RRLP-BL50W 2022-8-5(1)-改版.jpg",
        "gallery": [
            "images/cases/灯具包装盒/（新地址）底发光 595595 RRLP-BL50W 2022-8-5(1)-改版.jpg",
            "images/cases/灯具包装盒/暗装无边框面板灯彩盒_画板 1 副本 4.jpg",
            "images/cases/灯具包装盒/彩盒_暗装30W.jpg",
            "images/cases/灯具包装盒/奇正-D6349-PB10--更改彩盒色温名称、删除二类灯具图标-02.jpg",
            "images/cases/灯具包装盒/射灯包装内盒.jpg",
            "images/cases/灯具包装盒/DW-36 Octubre2022.jpg",
            "images/cases/灯具包装盒/PAN-38y43-A4-NE-Q-JUL2023.jpg",
            "images/cases/灯具包装盒/RR - LED TRACK LIGHT - 20W - INNER.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859952,
        "sortOrder": 61,
        "isTop": false,
        "title": "CCML logo设计",
        "category": "branding",
        "categoryName": "品牌设计",
        "displayStyle": "B",
        "image": "images/cases/CCML logo设计/1.jpg",
        "gallery": [
            "images/cases/CCML logo设计/1.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859953,
        "sortOrder": 63,
        "isTop": false,
        "title": "Pure color logo设计",
        "category": "branding",
        "categoryName": "品牌设计",
        "displayStyle": "B",
        "image": "images/cases/Pure color logo设计/00001.jpg",
        "gallery": [
            "images/cases/Pure color logo设计/00001.jpg",
            "images/cases/Pure color logo设计/5d6a409066b93.jpg",
            "images/cases/Pure color logo设计/5e0ea982957a0.jpg",
            "images/cases/Pure color logo设计/single_cup35002327.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859954,
        "sortOrder": 65,
        "isTop": false,
        "title": "一组logo设计",
        "category": "branding",
        "categoryName": "品牌设计",
        "displayStyle": "B",
        "image": "images/cases/一组logo设计/auto-orient_1 (4).jpg",
        "gallery": [
            "images/cases/一组logo设计/auto-orient_1 (4).jpg",
            "images/cases/一组logo设计/image22.jpeg",
            "images/cases/一组logo设计/image23.jpg",
            "images/cases/一组logo设计/image24.jpeg",
            "images/cases/一组logo设计/image25.jpg",
            "images/cases/一组logo设计/OJL.jpg",
            "images/cases/一组logo设计/Snipaste_2024-08-26_16-23-18.jpg",
            "images/cases/一组logo设计/ZHONGCHUANG .jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859955,
        "sortOrder": 67,
        "isTop": false,
        "title": "创宏智控系列品牌logo",
        "category": "branding",
        "categoryName": "品牌设计",
        "displayStyle": "B",
        "image": "images/cases/创宏智控系列品牌logo/BEAUTIFUL COLOR_LOGO.jpg",
        "gallery": [
            "images/cases/创宏智控系列品牌logo/BEAUTIFUL COLOR_LOGO.jpg",
            "images/cases/创宏智控系列品牌logo/BESTGEE.jpg",
            "images/cases/创宏智控系列品牌logo/KINGEE.jpg",
            "images/cases/创宏智控系列品牌logo/LASERCUBE.jpg",
            "images/cases/创宏智控系列品牌logo/PURE COLOR_LOGO.jpg",
            "images/cases/创宏智控系列品牌logo/TRUE COLOR_LOGO.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859956,
        "sortOrder": 69,
        "isTop": false,
        "title": "合鼎集团",
        "category": "branding",
        "categoryName": "品牌设计",
        "displayStyle": "B",
        "image": "images/cases/合鼎集团/7.jpg",
        "gallery": [
            "images/cases/合鼎集团/7.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859957,
        "sortOrder": 71,
        "isTop": false,
        "title": "琢光照明logo设计",
        "category": "branding",
        "categoryName": "品牌设计",
        "displayStyle": "B",
        "image": "images/cases/琢光照明logo设计/ZOOM LOGO_logo.jpg",
        "gallery": [
            "images/cases/琢光照明logo设计/ZOOM LOGO_logo.jpg",
            "images/cases/琢光照明logo设计/ZOOM LOGO.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859958,
        "sortOrder": 73,
        "isTop": false,
        "title": "Banner",
        "category": "dianshang",
        "categoryName": "电商设计",
        "displayStyle": "B",
        "image": "images/cases/Banner/场景banner.jpg",
        "gallery": [
            "images/cases/Banner/场景banner.jpg",
            "images/cases/Banner/超薄面板灯.jpg",
            "images/cases/Banner/法兰克福banner.jpg",
            "images/cases/Banner/三防灯.jpg",
            "images/cases/Banner/首页_35099ff0.jpg",
            "images/cases/Banner/首页.jpg",
            "images/cases/Banner/A8plusbanner 2.jpg",
            "images/cases/Banner/Banner2.jpg",
            "images/cases/Banner/image12.jpg",
            "images/cases/Banner/image13.jpeg",
            "images/cases/Banner/image13.jpg",
            "images/cases/Banner/image14.jpg",
            "images/cases/Banner/image15.jpg",
            "images/cases/Banner/image16.jpg",
            "images/cases/Banner/lc100.jpg",
            "images/cases/Banner/N4banner 1.jpg",
            "images/cases/Banner/T300SPRO.jpg",
            "images/cases/Banner/T400.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859959,
        "sortOrder": 75,
        "isTop": false,
        "title": "主图",
        "category": "dianshang",
        "categoryName": "电商设计",
        "displayStyle": "B",
        "image": "images/cases/主图/2 (2).jpg",
        "gallery": [
            "images/cases/主图/2 (2).jpg",
            "images/cases/主图/2x2ft-5Y-30mm.jpg",
            "images/cases/主图/3Y底发光.jpg",
            "images/cases/主图/600.jpg",
            "images/cases/主图/超薄灯体.jpg",
            "images/cases/主图/家装筒灯-主图2.jpg",
            "images/cases/主图/面板灯60x60-定制2.jpg",
            "images/cases/主图/面板灯60x60-主图1.jpg",
            "images/cases/主图/面板灯60x60-主图2.jpg",
            "images/cases/主图/面板灯60x60-主图4.jpg",
            "images/cases/主图/射灯-7-3-B.jpg",
            "images/cases/主图/H射灯-主图2.jpg",
            "images/cases/主图/main_14.jpg",
            "images/cases/主图/panel light 01.jpg",
            "images/cases/主图/panel light 04.jpg",
            "images/cases/主图/panel light 09.jpg",
            "images/cases/主图/panel light 10.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859960,
        "sortOrder": 77,
        "isTop": false,
        "title": "详情页",
        "category": "dianshang",
        "categoryName": "电商设计",
        "displayStyle": "B",
        "image": "images/cases/详情页/电脑主机详情页.jpg",
        "gallery": [
            "images/cases/详情页/电脑主机详情页.jpg",
            "images/cases/详情页/射灯详情页.jpg",
            "images/cases/详情页/音响详情页.jpg",
            "images/cases/详情页/琢光企业详情页.jpg",
            "images/cases/详情页/E12PLUS详情页英文.jpg",
            "images/cases/详情页/N4详情页.jpg",
            "images/cases/详情页/N7详情页1000.jpg",
            "images/cases/详情页/N7详情页英文版.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859961,
        "sortOrder": 79,
        "isTop": false,
        "title": "135广交会照明展物料",
        "category": "offline",
        "displayStyle": "B",
        "subtitle": "",
        "image": "images/cases/135广交会现场/135广交会正面灯箱内容1.jpg",
        "gallery": [
            "images/cases/135广交会现场/135广交会正面灯箱内容1.jpg",
            "images/cases/135广交会现场/135广交会正面灯箱内容.jpg",
            "images/cases/135广交会现场/135广交会顶部灯箱-01.jpg",
            "images/cases/135广交会现场/135广交会顶部灯箱-02.jpg",
            "images/cases/135广交会现场/135广交会现场.jpg",
            "images/cases/135广交会现场/135广交会现场2.jpg",
            "images/cases/135广交会现场/135广交会现场3.jpg",
            "images/cases/135广交会现场/135广交会正面灯箱内容_画板 1 .jpg"
        ],
        "description": "",
        "tags": []
    },
    {
        "id": 1788513859962,
        "sortOrder": 81,
        "isTop": false,
        "title": "3d打印产品物料",
        "category": "offline",
        "categoryName": "线下物料",
        "displayStyle": "B",
        "image": "images/cases/3d打印产品物料/ET4英文单页转曲_1.jpg",
        "gallery": [
            "images/cases/3d打印产品物料/ET4英文单页转曲_1.jpg",
            "images/cases/3d打印产品物料/ET4英文单页转曲_2.jpg",
            "images/cases/3d打印产品物料/image17.jpg",
            "images/cases/3d打印产品物料/image18.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859963,
        "sortOrder": 83,
        "isTop": false,
        "title": "3d打印展会背景墙",
        "category": "offline",
        "categoryName": "线下物料",
        "displayStyle": "B",
        "image": "images/cases/3d打印展会背景墙/微信图片_202009052030188.jpg",
        "gallery": [
            "images/cases/3d打印展会背景墙/微信图片_202009052030188.jpg",
            "images/cases/3d打印展会背景墙/微信图片_2020090520301814.jpg",
            "images/cases/3d打印展会背景墙/微信图片_2020090520301815.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859964,
        "sortOrder": 85,
        "isTop": false,
        "title": "婚博会展位背景墙物料",
        "category": "offline",
        "categoryName": "线下物料",
        "displayStyle": "B",
        "image": "images/cases/婚博会展位背景墙物料/70X100cm广告sg.jpg",
        "gallery": [
            "images/cases/婚博会展位背景墙物料/70X100cm广告sg.jpg",
            "images/cases/婚博会展位背景墙物料/背景墙样机.jpg",
            "images/cases/婚博会展位背景墙物料/微信图片_20240725172850.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859965,
        "sortOrder": 87,
        "isTop": false,
        "title": "灯具展会物料",
        "category": "offline",
        "categoryName": "线下物料",
        "displayStyle": "B",
        "image": "images/cases/灯具展会物料/光亚展邀请函2.jpg",
        "gallery": [
            "images/cases/灯具展会物料/光亚展邀请函2.jpg",
            "images/cases/灯具展会物料/邀请函.jpg",
            "images/cases/灯具展会物料/IMG_0044.jpg",
            "images/cases/灯具展会物料/IMG_0045.jpg",
            "images/cases/灯具展会物料/IMG_0046.JPG",
            "images/cases/灯具展会物料/IMG_1975.jpg",
            "images/cases/灯具展会物料/IMG_5511.HEIC.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859966,
        "sortOrder": 89,
        "isTop": false,
        "title": "照明产品折页",
        "category": "offline",
        "categoryName": "线下物料",
        "displayStyle": "B",
        "image": "images/cases/照明产品折页/奇正折页1.jpg",
        "gallery": [
            "images/cases/照明产品折页/奇正折页1.jpg",
            "images/cases/照明产品折页/奇正折页2.jpg",
            "images/cases/照明产品折页/奇正折页3.jpg",
            "images/cases/照明产品折页/奇正折页4.jpg",
            "images/cases/照明产品折页/奇正折页5.jpg",
            "images/cases/照明产品折页/奇正折页6.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859967,
        "sortOrder": 91,
        "isTop": false,
        "title": "照明挪威展 展板背景墙",
        "category": "offline",
        "categoryName": "线下物料",
        "displayStyle": "B",
        "image": "images/cases/照明挪威展 展板背景墙/挪威展2.jpg",
        "gallery": [
            "images/cases/照明挪威展 展板背景墙/挪威展2.jpg",
            "images/cases/照明挪威展 展板背景墙/样机.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    },
    {
        "id": 1788513859968,
        "sortOrder": 93,
        "isTop": false,
        "title": "门店活动物料",
        "category": "offline",
        "categoryName": "线下物料",
        "displayStyle": "B",
        "image": "images/cases/门店活动物料/46.5x68关于我们sg2.jpg",
        "gallery": [
            "images/cases/门店活动物料/46.5x68关于我们sg2.jpg",
            "images/cases/门店活动物料/爱贝和美海报sg.jpg",
            "images/cases/门店活动物料/分娩课指引牌.jpg",
            "images/cases/门店活动物料/空中瑜伽sg.jpg",
            "images/cases/门店活动物料/微信图片_20240725172835.jpg",
            "images/cases/门店活动物料/微信图片_20240725172841.jpg",
            "images/cases/门店活动物料/微信图片_20240725172845.jpg",
            "images/cases/门店活动物料/易拉宝样机.jpg",
            "images/cases/门店活动物料/征稿启示.jpg",
            "images/cases/门店活动物料/KT板样机.jpg"
        ],
        "subtitle": "",
        "description": "",
        "challenge": "",
        "solution": "",
        "results": [],
        "features": [],
        "tags": []
    }
];

function sortProjects(projects) {
    return [...projects].sort((a, b) => {
        if (a.isTop && !b.isTop) return -1;
        if (!a.isTop && b.isTop) return 1;
        return (b.sortOrder || 0) - (a.sortOrder || 0);
    });
}

const sortedProjects = sortProjects(projectsData);
const featuredWorks = sortedProjects.slice(0, 8);

const categories = {
    "branding": "品牌设计",
    "ui": "UI设计",
    "packaging": "包装设计",
    "dianshang": "电商设计",
    "3d": "3D渲染",
    "aigc": "AIGC",
    "photography": "产品摄影",
    "offline": "线下物料"
};

const blogCategories = {
    "design-trends": "设计趋势",
    "ui-design": "UI设计",
    "packaging": "包装设计",
    "ecommerce": "电商设计",
    "branding": "品牌设计",
    "tips": "设计技巧"
};

const presetTags = [
    "品牌策略",
    "VI设计",
    "视觉系统",
    "UI设计",
    "UX设计",
    "交互设计",
    "移动端",
    "包装设计",
    "结构设计",
    "电商设计",
    "视觉营销",
    "数据分析",
    "品牌设计",
    "空间设计",
    "动效设计",
    "视觉设计",
    "VI系统",
    "用户研究",
    "生产指导",
    "页面优化",
    "营销设计",
    "信息架构",
    "响应式设计",
    "场景化设计",
    "产品实拍",
    "3D渲染",
    "AIGC",
    "产品摄影",
    "线下物料"
];

function getCategoryName(category) {
    return categories[category] || category;
}

function getProjectById(id) {
    return projectsData.find(project => project.id === parseInt(id));
}

window.blogPosts = [
    {
        "slug": "2024-brand-trends",
        "fileName": "2024-brand-trends.md",
        "title": "2024-brand-trends",
        "date": "",
        "category": "",
        "author": "",
        "cover": "",
        "excerpt": "",
        "tags": []
    },
    {
        "slug": "brand-vi-guide",
        "fileName": "brand-vi-guide.md",
        "title": "brand-vi-guide",
        "date": "",
        "category": "",
        "author": "",
        "cover": "",
        "excerpt": "",
        "tags": []
    },
    {
        "slug": "color-theory",
        "fileName": "color-theory.md",
        "title": "color-theory",
        "date": "",
        "category": "",
        "author": "",
        "cover": "",
        "excerpt": "",
        "tags": []
    },
    {
        "slug": "ecommerce-design",
        "fileName": "ecommerce-design.md",
        "title": "ecommerce-design",
        "date": "",
        "category": "",
        "author": "",
        "cover": "",
        "excerpt": "",
        "tags": []
    },
    {
        "slug": "packaging-design",
        "fileName": "packaging-design.md",
        "title": "packaging-design",
        "date": "",
        "category": "",
        "author": "",
        "cover": "",
        "excerpt": "",
        "tags": []
    },
    {
        "slug": "ui-ux-tips",
        "fileName": "ui-ux-tips.md",
        "title": "ui-ux-tips",
        "date": "",
        "category": "",
        "author": "",
        "cover": "",
        "excerpt": "",
        "tags": []
    }
];

function getBlogPostById(id) {
    return window.blogPosts.find(post => post.id === parseInt(id));
}